# Attention Mechanism

## a simple attention mechanism without trainning


In [1]:
"hello world"

'hello world'

In [2]:
import torch
inputs = torch.tensor(
[[0.43, 0.15, 0.89], #your (x^1)
[0.55, 0.87, 0.66], #journey (x^2)
[0.57, 0.85, 0.64], #starts (x^3)
[0.22, 0.58, 0.33], #with (x^4)
[0.77, 0.25, 0.10], #one (x^5)
[0.05, 0.80, 0.55]]) #step (x^6)

print(inputs)



tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])


In [3]:
print(inputs[1])

tensor([0.5500, 0.8700, 0.6600])


In [4]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
    print(str(x_i)+"  ==>  "+str(query))
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.4300, 0.1500, 0.8900])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.5500, 0.8700, 0.6600])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.5700, 0.8500, 0.6400])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.2200, 0.5800, 0.3300])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.7700, 0.2500, 0.1000])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.0500, 0.8000, 0.5500])  ==>  tensor([0.5500, 0.8700, 0.6600])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [5]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


In [7]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

softmax_naive(attn_scores_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [ ]:
attn_weights_2 = torch.softmax(attn_score_2, dim=0)

In [ ]:
context_vec_2 = torch.zeros(query.shape)
context_vec_2

tensor([0., 0., 0.])

In [ ]:
query = inputs[1]

for ind,x in enumerate(inputs):
    context_vec_2+=attn_weights_2[ind]*inputs[ind]
print("This is the context vector: which is calculated using the attention weights and inputs using the dot product")
context_vec_2

This is the context vector: which is calculated using the attention weights and inputs using the dot product


tensor([0.8837, 1.3030, 1.1366])

- Now, let's create a simple attention mechanism : with the help Wq, Wk, Wv which refers to query, key, value.

In [10]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2
print("d_in - ", d_in)
print("d_out - ", d_out)
print("x_2 - ", x_2)

d_in -  3
d_out -  2
x_2 -  tensor([0.5500, 0.8700, 0.6600])


In [12]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

print("W_query - ", W_query)
print("W_key - ", W_key)
print("W_value - ", W_value)


W_query -  Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])
W_key -  Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])
W_value -  Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])


In [13]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)

tensor([0.4306, 1.4551])


In [14]:
keys = inputs @ W_key
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [15]:
keys_2 = keys[1]
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8524)


In [16]:
attn_scores_2 = query_2 @ keys.T
print(attn_scores_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [17]:
d_k = keys.shape[-1]
print(d_k)

2


In [18]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])


In [19]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.3061, 0.8210])


In [ ]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))
    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T 
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [21]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)


In [22]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
        attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [ ]:
torch.manual_seed(789)
sav_v2 = SelfAttention_v2(d_in,d_out)
print(sav_v2(inputs))

tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)
